---
title: "assignment2"
author: "Cade Garcia"
date: "2025-08-07"
output: html_document
---

```{r}
library(shiny)
library(mapgl)
library(here)
library(sf)
library(viridis)
library(tidyverse)
library(bslib)
```

```{r}
county_data <- st_read(here("data/county_data.gpkg"))
```

```{r}
language_vars <- county_data %>%
  st_drop_geometry() %>%
  select(contains("english"), contains("spanish"), contains("hawaiian"), contains("japanese")) %>%
  select(where(is.numeric)) %>%
  names()

# UI
ui <- page_sidebar(
  titlePanel("County Map Viewer"),
  sidebarLayout(
    sidebarPanel(
      selectInput("var", "Choose a variable to map:", choices = language_vars)
    ),
    card(
      full_screen = TRUE,
      maplibreOutput("map")
    )
  )
)

# Server
server <- function(input, output, session) {

  output$county_map <- renderMaplibre({
    req(input$var)

    # Drop NAs
    plot_data <- county_data %>% filter(!is.na(.data[[input$var]]))

    # Normalize selected variable for color scaling
    vals <- plot_data[[input$var]]
    pal <- viridis(length(vals), option = "C")

    plot_data <- plot_data %>%
      mutate(
        color = pal[rank(vals, ties.method = "first")]
      )

    # Render map
    map_widget <- mapgl() %>%
      add_fill(
        data = plot_data,
        color = plot_data$color,
        popup = paste0(input$var, ": ", round(vals, 2))
      ) %>%
      add_navigation()
    
      
    mapgl::as_widget(map_widget)

  })
}

# Run the app 
shinyApp(ui, server)

```
